package com.gorillalogic.salesforce.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.gorillalogic.salesforce.converter.LocalDateTimeConverter;
import com.gorillalogic.salesforce.enums.AccountEnums;
import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Account")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Account {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String ownerId;

    @DynamoDBAttribute
    private String salesOwnerId;

    @DynamoDBAttribute
    private String parentAccountId;

    @DynamoDBAttribute
    private Boolean canReference;

    @DynamoDBAttribute
    private Integer wonOpportunityCount;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.CurrencyCode currencyCode;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime firstWonDate;

    @DynamoDBAttribute
    private String financialAnalystId;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.Status status;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String fax;

    @DynamoDBAttribute
    private String websiteUrl;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.AccountSource accountSource;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.AccountRecordTye accountRecordTye;

    @DynamoDBAttribute
    private Integer invoicingTermDays;

    @DynamoDBAttribute
    private String msaDocUrl;

    @DynamoDBAttribute
    private String msaDocAddendumUrl;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.Type type;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.Industry industry;

    @DynamoDBAttribute
    private String description;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private AccountEnums.EmployeeRange employeeRange;

    @DynamoDBAttribute
    private Double annualRevenue;

    @DynamoDBAttribute
    private String billingAddress;

    @DynamoDBAttribute
    private String shippingAddress;

    @DynamoDBAttribute
    private String createdById;

    @DynamoDBAttribute
    private String lastModifiedById;

}
