package com.gorillalogic.salesforce.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.gorillalogic.salesforce.converter.LocalDateTimeConverter;
import com.gorillalogic.salesforce.enums.CandidateEnums;
import com.gorillalogic.salesforce.enums.ContactEnums;
import lombok.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Contact")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Contact {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.Type type;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String mobile;

    @DynamoDBAttribute
    private String email;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.RecordType recordType;

    @DynamoDBAttribute
    private String mailingAddress;

    @DynamoDBAttribute
    private String createdById;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdOnDate;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String accountId;

    @DynamoDBAttribute
    private String ownerUserId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private Boolean doNotCall;

    @DynamoDBAttribute
    private Integer websiteVisits;

    @DynamoDBAttribute
    private Boolean blogFirstWebContact;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.Role role;

    @DynamoDBAttribute
    private Integer itDepartmentSize;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.CurrencyCode currencyCode;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.LeadSource leadSource;

    @DynamoDBAttribute
    private String leadSourceDetail;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private ContactEnums.RevenueFunnelStatus revenueFunnelStatus;
}
