package com.gorillalogic.salesforce.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;
import org.springframework.stereotype.Service;

@DynamoDBTable(tableName = "User")
@Getter
@Setter
@AllArgsConstructor
@ToString
public class DynamoUser {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    public DynamoUser(String name) {
        this.name = name;
    }
}
