package com.gorillalogic.salesforce.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;
import org.springframework.stereotype.Service;

import javax.validation.constraints.Email;

@DynamoDBTable(tableName = "User")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String accountId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String aboutMe;

    @DynamoDBAttribute
    private String legacyUserId;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private String managerUserId;

    @DynamoDBAttribute
    private String companyName;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String mobile;

    @DynamoDBAttribute
    private String fullPhotoUrl;

    @DynamoDBAttribute
    private String mediumPhotoUrl;

    @DynamoDBAttribute
    private String smallPhotoUrl;

    @DynamoDBAttribute
    private String iosPhotoUrl;

    @DynamoDBAttribute
    private String androidPhotoUrl;

    public User(String name) {
        this.name = name;
    }
}
